- name: "{{ application_name }}: set variables"
  set_fact:
      controller_account_per_controller: "{{ config_data.controller_account_per_controller }}"
      script_runner: "{{ config_data.script_runner }}"
      tripleo_db_user: "{{ config_data.tripleo_db_user }}"
      tripleo_db_url: "{{ config_data.tripleo_db_url }}"
      container_account_per_controller: "{{ config_data.container_account_per_controller }}"
      config_file: "{{ config_data.controller_config_file }}"

- name: "{{ application_name }}: generate new URL from tripleo_db_url"
  shell: "{{ script_content }}"
  vars:
    script_content: |
      cat << EOF | {{ script_runner }} python
      from __future__ import print_function
      from sqlalchemy.engine import url
      u = url.make_url("{{ tripleo_db_url }}")
      u.username = None
      u.password = None
      u.host = None
      u.query.update(read_default_file="{{ container_account_per_controller }}", read_default_group="{{ application_name }}")
      print(u)
      EOF
  register: apc_url_command_output

- name: "{{ application_name }}: write URL into service conf file"
  ini_file:
    path: "{{ config_file }}"
    section: "{{ config_data.section_name }}"
    option: "{{ config_data.parameter_name }}"
    value: "{{ apc_url_command_output.stdout_lines[0] }}"

