- name: get local IP number of controller
  shell: |
    HOSTNAME=`hostname`

    # use ahostsv6 for ipv6...
    LOCAL_IP=`getent ahostsv4 ${HOSTNAME} | grep ${HOSTNAME} | awk '{ print $1 }'`
    echo "${LOCAL_IP}"
  register: local_ipcommand_output

# note we rely upon command -v failing if neither can be found
- name: determine docker or podman
  shell: command -v podman docker
  register: container_command_output

- name: store facts
  set_fact:
    container_cli: "{{ container_command_output.stdout_lines[0] }}"
    local_ip_address: "{{ local_ipcommand_output.stdout }}"
    local_mysql_port: 3307

- name: get MySQL root password from hiera
  shell: /bin/hiera -c /etc/puppet/hiera.yaml "mysql::server::root_password"
  register: hiera_root_output

- name: get local galera container name
  shell: |
    {{ container_cli }} ps --format \{\{'.Names'\}\} --filter name=galera
  register: galera_container_output

- name: set local galera container name, mysql command
  set_fact:
    galera_container: "{{ galera_container_output.stdout_lines[0] }}"
    mysql_root_password: "{{ hiera_root_output.stdout_lines[0] }}"
    mysql_cli: "{{ container_cli }} exec -i {{ galera_container_output.stdout_lines[0] }} mysql -u root --password={{ hiera_root_output.stdout_lines[0] }} -Ns -e"

- name: "{{ item.name }}: gather other facts for reuse"
  include_tasks: gather_conf_facts.yml
  loop_control:
    loop_var: gather_conf_item
  vars:
    application_name: "{{ gather_conf_item.key }}"
    config_data: "{{ gather_conf_item.value }}"
  with_dict: "{{ config_locations }}"

- name: "print config data"
  debug:
    msg: "{{ gather_conf_item }}"
  loop_control:
    loop_var: gather_conf_item
  with_dict: "{{ config_locations }}"
  when: "{{ gather_conf_item.value.present | bool }}"

