- name: run install
  gather_facts: false
  hosts: controllers
  become: yes
  become_user: root
  roles:
    - { role: setup_facts, tags: ['always']}
    - { role: revert_service_urls, tags: ['revert-service-urls', 'write-service-urls']}
    - { role: update_nova_cells, tags: ['update-nova-cells'], vars: {revert_nova_cells: true}}
    - { role: restart_containers, tags: ['restart-containers']}
    - { role: alter_tripleo_mysql_grants, tags: ['restore-tripleo-mysql-grants'], vars: {enable_ooo_grants: true}}


