- name: run install
  gather_facts: false
  hosts: controllers
  become: yes
  become_user: root
  roles:
    - { role: setup_facts, tags: ['always', 'setup-facts']}
    - { role: update_haproxy, tags: ['update-haproxy']}
    - { role: write_apc_conf, tags: ['write-apc-conf']}
    - { role: create_mysql_grants, tags: ['create-mysql-grants']}
    - { role: write_service_urls, tags: ['write-service-urls']}
    - { role: update_nova_cells, tags: ['update-nova-cells'], vars: {convert_nova_cells: true}}
    - { role: restart_containers, tags: ['restart-containers']}
    - { role: alter_tripleo_mysql_grants, tags: ['drop-tripleo-mysql-grants'], vars: {enable_ooo_grants: false}}


