
- name: "{{ item.name }}: alter tripleo-level grants"
  include_tasks: alter_ooo_mysql_grant.yml
  vars:
    application_name: "{{ item.name }}"
    database_name: "{{ item.name }}"
    puppet_config_name: "{{ item.puppet_config_name }}"
    hiera: "{{ item.hiera }}"
    config: "{{ item.config }}"
    section_name: "{{ item.section_name }}"
    parameter_name: "{{ item.parameter_name }}"
    local_ip: "{{ ip_number }}"
    containers: "{{ item.containers }}"
  with_items: "{{ config_locations }}"

