
- name: "{{ item.name }}: rewrite puppet-generated conf file on controller"
  include_tasks: revert_service_conf.yml
  loop_control:
    loop_var: write_service_item
  vars:
    application_name: "{{ write_service_item.key }}"
    config_data: "{{ write_service_item.value }}"
  with_dict: "{{ config_locations }}"
  when: "{{ write_service_item.value.present | bool }}"
