- name: "{{ application_name }}: see if puppet config for applcation exists"
  stat:
    path: "{{ openstack_controller_puppet_generated }}/{{ puppet_config_name }}"
  register: puppet_config_stat

- block:
    - name: "{{ application_name }}: find a container image we can use to run commands"
      shell: |
        {{ container_cli }} ps --format \{\{'.Image'\}\} --filter name={{ containers[0] }}
      register: command_output

    - name: "{{ application_name }}: determine a script runner docker image"
      set_fact:
        container_image: "{{ command_output.stdout_lines[0] }}"
        script_runner: "{{ container_cli }} run -i -u root -v '{{ openstack_controller_puppet_generated }}/{{ puppet_config_name }}:{{ openstack_controller_puppet_generated }}/{{ puppet_config_name }}' {{ command_output.stdout_lines[0] }}"

    - name: "{{ application_name }}: set puppet-generated file location"
      set_fact:
          config_file: "{{ openstack_controller_puppet_generated }}/{{ puppet_config_name }}{{ config }}"
      when: puppet_config_name is defined

    - name: "{{ application_name }}: set non-puppet-generated file location"
      set_fact:
          config_file: "{{ config }}"
      when: puppet_config_name is not defined

    - name: "{{ application_name }}: read tripleo configured database URL from hiera"
      shell: |
        URL=`hiera -c /etc/puppet/hiera.yaml "{{ hiera }}"`
        if [[ "${URL}" == "nil" ]]; then
          exit -1
        else
          echo "${URL}"
        fi
      register: existing_url_command_output

    - name: "{{ application_name }}: write URL into service conf file"
      ini_file:
        path: "{{config_file }}"
        section: "{{ section_name }}"
        option: "{{ parameter_name }}"
        value: "{{ existing_url_command_output.stdout_lines[0] }}"
  when: puppet_config_stat.stat.exists

