- name: get haproxy container name
  shell: |
    {{ container_cli }} ps --format \{\{'.Names'\}\} --filter name=haproxy
  register: command_output

- name: add a local IP bind for haproxy
  lineinfile:
    path: "{{ openstack_controller_puppet_generated }}/haproxy/etc/haproxy/haproxy.cfg"
    line: "  bind {{ local_ip_address }}:3307"
    insertafter: "listen mysql"

- name: restart haproxy
  shell: |
    {{ container_cli }} restart {{ command_output.stdout_lines[0] }}
