- name: get haproxy container name
  # we are trying to ensure we don't grab names like "neutron-haproxy-qrouter".
  # not sure how to locate other names that might exist.  so ensure "haproxy" is
  # at the start of the string w/ an extra grep
  shell: |
    {{ container_cli }} ps --format \{\{'.Names'\}\} --filter name=haproxy-bundle | grep -e "^haproxy"
  register: command_output

- name: add a local IP bind for haproxy
  lineinfile:
    path: "{{ openstack_controller_puppet_generated }}/haproxy/etc/haproxy/haproxy.cfg"
    line: "  bind {{ local_ip_address }}:3307"
    insertafter: "listen mysql"
    seuser: "{{ etc_seuser }}"
    serole: "{{ etc_serole }}"
    setype: "{{ etc_setype }}"

- name: restart haproxy
  shell: |
    {{ container_cli }} restart {{ command_output.stdout_lines[0] }}
  when: command_output.stdout_lines | length > 0
