
- name: get MySQL root password from hiera
  shell: /bin/hiera -c /etc/puppet/hiera.yaml "mysql::server::root_password"
  register: hiera_root_output

- name: get local galera container name
  shell: |
    {{ container_cli }} ps --format \{\{'.Names'\}\} --filter name=galera
  register: galera_container_output

- name: set local galera container name, mysql command
  set_fact:
    galera_container: "{{ galera_container_output.stdout_lines[0] }}"
    mysql_root_password: "{{ hiera_root_output.stdout_lines[0] }}"
    mysql_cli: "{{ container_cli }} exec -i {{ galera_container_output.stdout_lines[0] }} mysql -u root --password={{ hiera_root_output.stdout_lines[0] }} -Ns -e"

- name: "{{ item.name }}: rewrite puppet-generated conf file on controller"
  include_tasks: write_conf.yml
  vars:
    application_name: "{{ item.name }}"
    puppet_config_name: "{{ item.puppet_config_name }}"
    config: "{{ item.config }}"
    section_name: "{{ item.section_name }}"
    parameter_name: "{{ item.parameter_name }}"
    local_ip: "{{ ip_number }}"
    containers: "{{ item.containers }}"
  with_items: "{{ config_locations }}"

