# write_conf
# receives variables:
#    application_name
#    puppet_config_name
#    config: config file path relative to a server or container
#    section_name: "{{ item.section_name }}"
#    parameter_name: "{{ item.parameter_name }}"
#    local_ip: "{{ ip_number }}"

- name: "{{ application_name }}: set puppet-generated file location"
  set_fact:
      config_file: "{{ openstack_controller_puppet_generated }}/{{ puppet_config_name }}{{ config }}"
  when: puppet_config_name is defined

- name: "{{ application_name }}: set non-puppet-generated file location"
  set_fact:
      config_file: "{{ config }}"
  when: puppet_config_name is not defined

- name: "{{ application_name }}: read current SQLAlchemy URL for section"
  shell: |
      crudini --get {{ config_file }}  {{ section_name}}  {{ parameter_name }}
  register: command_output

- name: "{{ application_name }}: get URL"
  set_fact:
    existing_url: "{{ command_output.stdout }}"

