
- name: "{{ item.name }}: write account_per_controller.cnf file on controller"
  include_tasks: write_apc_conf.yml
  loop_control:
    loop_var: write_apc_item
  vars:
    application_name: "{{ write_apc_item.key }}"
    config_data: "{{ write_apc_item.value }}"
  with_dict: "{{ config_locations }}"
  when: "{{ write_apc_item.value.present | bool }}"
