
- name: "{{ item.name }}: create mysql grants"
  include_tasks: create_mysql_grants.yml
  loop_control:
    loop_var: write_service_item
  vars:
    application_name: "{{ write_service_item.key }}"
    config_data: "{{ write_service_item.value }}"
  with_dict: "{{ config_locations }}"
  when: write_service_item.value.present | bool

