openstack_controller_puppet_generated: /var/lib/config-data/puppet-generated

# selinux roles for files in etc
# not sure why these can't default correctly
# these only matter in osp15 / podman
# also not sure if i should get these from somehwere
etc_seuser: "unconfined_u"
etc_serole: "object_r"
etc_setype: "container_file_t"


config_locations:
  aodh:
    puppet_config_name: aodh_base
    hiera: "aodh::db::database_connection"
    config: /etc/aodh/aodh.conf
    section_name: database
    parameter_name: connection
    containers:
      - aodh_base

#  barbican:
#    puppet_config_name: barbican
#    hiera: ""
#    config:
#    section_name: database
#    parameter_name: connection
#    containers:
#
  cinder:
    puppet_config_name: cinder
    hiera: "cinder::database_connection"
    config: /etc/cinder/cinder.conf
    section_name: database
    parameter_name: connection
    containers:
      - cinder_api
      - cinder_api_cron
      - cinder_scheduler
      - cinder_volume
    # cinder-volume matches up to openstack-cinder-volume-podman-0 etc
    container_expressions:
      - cinder-volume
#
#  ec2-api:
#    puppet_config_name: ec2_api
#    hiera: ""
#    config:
#    section_name: database
#    parameter_name: connection
#    containers:
#
  gnocchi:
    puppet_config_name: gnocchi
    hiera: "gnocchi::db::database_connection"
    config: "/etc/gnocchi/gnocchi.conf"
    section_name: indexer
    parameter_name: url
    containers:
      - gnocchi_api
      - gnocchi_metricd
      - gnocchi_statsd

  glance:
    puppet_config_name: glance_api
    hiera: "glance::api::database_connection"
    config: /etc/glance/glance-api.conf
    section_name: database
    parameter_name: connection
    containers:
      - glance_api

  heat:
    puppet_config_name: heat
    hiera: "heat::database_connection"
    config: /etc/heat/heat.conf
    section_name: database
    parameter_name: connection
    extra_configs:
      - puppet_config_name: heat_api
        config: /etc/heat/heat.conf
        section_name: database
        parameter_name: connection

      - puppet_config_name: heat_api_cfn
        config: /etc/heat/heat.conf
        section_name: database
        parameter_name: connection

    containers:
      - heat_api
      - heat_api_cfn
      - heat_api_cron
      - heat_engine
      - heat_api


  ironic:
    puppet_config_name: ironic
    hiera: "ironic::db::database_connection"
    config: /etc/ironic/ironic.conf
    section_name: ironic_config
    parameter_name: connection
    containers:
      - ironic_api

  ironic_inspector:
    puppet_config_name: ironic_inspector
    hiera: "ironic::inspector::db::database_connection"
    config: /etc/ironic-inspector/inspector.conf
    section_name: ironic_inspector_config
    parameter_name: connection
    containers:
      - ironic_inspector

  keystone:
    puppet_config_name: keystone
    hiera: "keystone::database_connection"
    config: /etc/keystone/keystone.conf
    section_name: database
    parameter_name: connection
    containers:
      - keystone
      - keystone_cron

  manila:
    puppet_config_name: manila
    hiera: "manila::db::database_connection"
    config: /etc/manila/manila.conf
    section_name: manila_config
    parameter_name: connection
    containers:
      - manila_api

  mistral:
    puppet_config_name: mistral
    hiera: "mistral::database_connection"
    config: /etc/mistral/mistral.conf
    section_name: database
    parameter_name: connection
    containers:
      - mistral_api
      - mistral_engine
      - mistral_event_engine
      - mistral_executor


  neutron:
    puppet_config_name: neutron
    hiera: "neutron::server::database_connection"
    config: /etc/neutron/neutron.conf
    section_name: database
    parameter_name: connection
    containers:
      - neutron
      - neutron_api

  neutron_plumgrid:
    puppet_config_name: neutron_plugin_plumgrid
    hiera: "neutron::plugins::plumgrid::connection"
    config: /etc/neutron/plugins/plumgrid/plumgrid.ini
    section_name: database
    parameter_name: connection
    containers:
      - neutron_plugin_plumgrid

  # for nova, both the nova and nova_api services use the same puppet
  # generated conf file.  nova_placement is separate.
  nova:
    # config name gives us /var/lib/config-data/puppet-generated/nova/etc/my.cnf.d/account_per_controller.cnf
    puppet_config_name: nova
    hiera: "nova::database_connection"
    config: /etc/nova/nova.conf
    section_name: database
    parameter_name: connection
    containers:
      - nova_conductor
      - nova_metadata
      - nova_scheduler
      - nova_consoleauth
    extra_configs:
        # write the nova URL into the nova_placement/nova.conf file
      - puppet_config_name: nova_placement
        config: /etc/nova/nova.conf
        section_name: database
        parameter_name: connection

    # write into other account_per_controller files too
    write_to_other_apcs:
      - nova_placement

  nova_api:
    puppet_config_name: nova
    hiera: "nova::api_database_connection"
    config: /etc/nova/nova.conf
    section_name: api_database
    parameter_name: connection
    containers:
      - nova_api
      - nova_api_cron
    extra_configs:
        # write the nova_api URL into the nova_placement/nova.conf file
      - puppet_config_name: nova_placement
        config: /etc/nova/nova.conf
        section_name: api_database
        parameter_name: connection
    write_to_other_apcs:
      - nova_placement

  # note that nova_placement in OSP13 is placement in OSP15
  nova_placement:
    puppet_config_name: nova_placement
    hiera: "nova::placement_database_connection"
    config: /etc/nova/nova.conf
    section_name: placement_database
    parameter_name: connection
    containers:
      - nova_placement
    extra_configs:
      # copy back placement into the main nova service, it is likely not
      # used however we want to remove all occurrences of the old username
      - puppet_config_name: nova
        config: /etc/nova/nova.conf
        section_name: placement_database
        parameter_name: connection
    write_to_other_apcs:
      - nova


#  octavia:
#    puppet_config_name: octavia
#    hiera: ""
#   config:
#    section_name: database
#    parameter_name: connection
#    containers:
#
#    # OSP15 and above
  placement:
    puppet_config_name: placement
    hiera: "placement::db::database_connection"
    config: /etc/placement/placement.conf
    section_name: placement_database
    parameter_name: connection
    containers:
      - placement

#  sahara:
#    puppet_config_name: sahara
#    hiera: ""
#    config:
#    section_name: database
#    parameter_name: connection
#    containers:
#
#  tacker:
#    puppet_config_name: tacker
#    hiera: ""
#    config:
#    section_name: database
#    parameter_name: connection
#    containers:
#      -
  zaqar:
    puppet_config_name: zaqar
    hiera: "zaqar::management::sqlalchemy::uri"
    config: /etc/zaqar/zaqar.conf
    section_name: drivers:storage:sqlalchemy
    parameter_name: uri
    containers:

